### ISSUE TITLE
Can't map signal to command in SignalCommand::execute()

### ISSUE THREAD

**Issue by Nek** [joelhooks/signals-extensions-CommandSignal#4] opened 2010-05-31 15:47 UTC
If I move this line
signalCommandMap.mapSignalClass(OrderReceived, FindOrderDetails);
from context startup into StartListenToOrders command the mapping breaks.

**Comment by joelhooks** [comment] 2010-05-31 16:22
It is impossible to say what the issue is out of context like this. Need more details, sample code, etc.

**Comment by Nek** [comment] 2010-05-31 16:24
Yep. Have added this one in haste. I'll provide details later on.

**Comment by joelhooks** [comment] 2010-11-07 15:57
I am closing this lacking more details

**Comment by Nek** [comment] 2010-11-07 16:10
I agree. As far as I remember the issue was fixed with the update of robotlegs/as3signals. Sorry for not writing it here in a comment earlier.

**Comment by joelhooks** [comment] 2010-11-07 16:17
It is more my neglect as a project parent. No worries :>

**Closed as completed** 2010-11-07 23:57 UTC

**Comment by Nek** [comment] 2010-11-08 09:54
ok )
